# Massa: The Decentralized and Scaled Blockchain

Massa is a truly decentralized blockchain controlled by thousands of people. 
With the breakthrough multithreaded technology, we’re set for mass adoption.


## Introduction

link:https://massa.net[Massa] is a new blockchain reaching a high transaction throughput in a decentralized network. 
Our research is published in this link:https://arxiv.org/pdf/1803.09029[technical paper].
It shows that a throughput of 10'000 transactions per second is reached even in a fully decentralized network with thousands of nodes.

An easy-to-read blog post introduction with videos is written link:https://massa.net/blog/post/0/[here].

We are now releasing the **Massa testnet** in this Gitlab repository, with its explorer available at link:https://test.massa.net[test.massa.net].


## Testnet Incentives

As decentralization is our core value, we would like to help you start and run a Massa node. 
Running a node during the testnet phase also helps us finding bugs and improving usability, so it will be rewarded with real Massa on mainnet launch. 

The mechanics of those rewards are described in the link:docs/testnet_rules.adoc[Testnet rules].
 

## Testnet Discussions

Please come to our link:https://discord.com/invite/TnsJQzXkRN[Discord] for testnet discussions, in the testnet channel.

For project announcements we mainly use link:https://t.me/massanetwork[Telegram]. 

## Install

If you just wish to run a Massa node without compiling it yourself, you can run the latest binary:

- link:https://gitlab.com/massalabs/massa/-/jobs/artifacts/testnet/download?job=build-windows[Windows executable]
- link:https://gitlab.com/massalabs/massa/-/jobs/artifacts/testnet/download?job=build-linux[Linux binary]
- link:https://gitlab.com/massalabs/massa/-/jobs/artifacts/testnet/download?job=build-darwin[MacOS binary]

### On Windows

Please go to the link:docs/windows_install.adoc[Install and Run on Windows] page.

### On Ubuntu / MacOS

* On Ubuntu, these libs must be installed: `sudo apt install pkg-config curl git build-essential libssl-dev`
* install link:https://www.rust-lang.org/tools/install[rustup] : `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
* configure path: `source $HOME/.cargo/env`
* check rust version: `rustc --version`
* install link:https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html[nigthly]: `rustup toolchain install nightly`
* set it as default: `rustup default nightly`
* check rust version: `rustc --version`
* clone this repo: `git clone --branch testnet https://gitlab.com/massalabs/massa.git`

## Run

### Start the node

On a first window:
----
cd massa/massa-node/
----

Launch the node, on Ubuntu:
----
RUST_BACKTRACE=full cargo run --release |& tee logs.txt
----

On MacOS: 
----
RUST_BACKTRACE=full cargo run --release > logs.txt 2>&1
----

### Start the client

On a second window:
----
cd massa/massa-client/
cargo run --release
----


## Update
----
cd massa/
git stash
git checkout testnet
git pull
----

## Tutorials

Here is a set of tutorials:

* link:docs/wallet.adoc[Creating a wallet]
* link:docs/staking.adoc[Staking]
* link:docs/transaction.adoc[Sending transactions]
* link:docs/windows_install.adoc[Install and Run on Windows]
* link:docs/routability.adoc[Routability tutorial]
* link:docs/testnet_rules.adoc[Testnet rewards program]
* To get testnet coins, send your address to the faucet bot in the "testnet-token-request" channel of our link:https://discord.com/invite/TnsJQzXkRN[Discord].


## FAQ and Troubleshooting

You'll find answer to common issues and questions regarding the Massa protocol in the link:docs/faq.adoc[FAQ].

Don't hesitate to ask questions in the link:https://discord.com/invite/TnsJQzXkRN[Discord] testnet channel.
