# Massa: The Decentralized and Scaled Blockchain

Massa is a truly decentralized blockchain controlled by thousands of people. 
With the breakthrough multithreaded technology, we’re set for mass adoption.


## Introduction

link:massa.net[Massa] is a new blockchain reaching a high transaction throughput in a decentralized network. 
Our research is published in this link:https://arxiv.org/pdf/1803.09029[technical paper].
It shows that a throughput of 10'000 transactions per second is reached even in a fully decentralized network with thousands of nodes.

An easy-to-read blog post introduction with videos is written link:https://massa.net/blog/post/0/)[here].

We are now releasing the **Massa testnet** in this Gitlab repository, with its explorer available at link:test.massa.net[test.massa.net].


## Testnet Incentives

As decentralization is our core value, we would like to help you start and run a Massa node. 
Running a node during the testnet phase also helps us finding bugs and improving usability, so it will be rewarded with real Massa on mainnet launch. 

The mechanics and amounts of those rewards are currently in discussion, the main idea is that the more block rewards you receive, the more Massa you will get at launch, with a per-person cap.
 

## Testnet Discussions

Please come to our link:https://discord.com/invite/TnsJQzXkRN[Discord] for testnet discussions, in the testnet channel.

For project announcements we mainly use link:https://t.me/massanetwork[Telegram]. 

## Install on ubuntu

* curl : `sudo apt install curl`
* link:https://www.rust-lang.org/tools/install[rustup] : `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
* configure path: `source $HOME/.cargo/env`
* check rust version: `rustc --version`
* install link:https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html[nigthly]: `rustup toolchain install nightly`
* set it as default: `rustup default nightly`
* check rust version: `rustc --version`
* install git: `sudo apt install git`
* clone this repo: `git clone https://gitlab.com/massalabs/massa-network.git`
* `sudo apt install build-essential`
* `sudo apt install libssl-dev`

## Run

### Start the node

----
cd massa-node/
RUST_BACKTRACE=full cargo run --release |& tee logs.txt
----


### Start the client

----
cd massa-client/
cargo run --release
----

### Tutorial

Here is a set of tutorials:

* link:docs/wallet.adoc[creating a wallet]
* link:docs/staking.adoc[staking]
* link:docs/transaction.adoc[sending transactions]

* Don't hesitate to ask testnet coins from us in the link:https://discord.com/invite/TnsJQzXkRN[Discord] testnet channel.
