// Copyright (c) 2023 MASSA LABS <info@massa.net>

use massa_time::MassaTime;
use std::path::PathBuf;

/// Client common settings.
/// the client common settings
#[derive(Debug, Clone)]
pub struct ClientConfig {
    /// maximum size in bytes of a request.
    pub max_request_body_size: u32,
    /// timeout of an request.
    pub request_timeout: MassaTime,
    /// maximum concurrent requests.
    pub max_concurrent_requests: usize,
    /// certificate_store, `Native` or `WebPki`
    ///
    /// Deprecated: this setting is currently ignored. The underlying `jsonrpsee` client no
    /// longer exposes a trust-store selection, and TLS is instead enabled by using an
    /// `https`/`wss` url, validated against the platform trust store. It is kept to avoid
    /// breaking existing configuration files.
    pub certificate_store: String,
    /// JSON-RPC request object id data type, `Number` or `String`
    pub id_kind: String,
    /// max length for logging for requests and responses. Logs bigger than this limit will be truncated.
    pub max_log_length: u32,
    /// custom headers to pass with every request.
    pub headers: Vec<(String, String)>,
}

/// Http client settings.
/// the Http client settings
#[derive(Debug, Clone)]
pub struct HttpConfig {
    /// common client configuration.
    pub client_config: ClientConfig,
    /// whether to enable HTTP.
    pub enabled: bool,
}

/// gRPC client TLS settings.
/// the gRPC client TLS settings
#[derive(Debug, Clone)]
pub struct GrpcTlsConfig {
    /// name under which the server certificate is verified, also used for SNI.
    /// TLS verification is name-based while the client dials an IP, so this must match
    /// one of the subject alternative names of the server certificate. The self-signed
    /// certificates generated by the node always include "localhost".
    pub server_name: String,
    /// path to the certificate authority root used to verify the server certificate.
    pub certificate_authority_root_path: PathBuf,
    /// path to the client certificate, only for mTLS (must be set together with
    /// `client_private_key_path`).
    pub client_certificate_path: Option<PathBuf>,
    /// path to the client private key, only for mTLS (must be set together with
    /// `client_certificate_path`).
    pub client_private_key_path: Option<PathBuf>,
}

/// Reject an mTLS configuration that does not also enable TLS.
///
/// mTLS is a strict extension of TLS: without this check, `enable_mtls` alone would
/// silently serve/connect in plaintext instead of authenticating with client
/// certificates. Shared between the gRPC server (massa-grpc) and the gRPC client
/// (massa-client), which each enforce this on their own TLS settings.
pub fn check_mtls_requires_tls(enable_tls: bool, enable_mtls: bool) -> Result<(), String> {
    if enable_mtls && !enable_tls {
        return Err(
            "`enable_mtls` requires `enable_tls` to be enabled, refusing to run in plaintext"
                .to_string(),
        );
    }
    Ok(())
}

/// WebSocket client settings.
/// the WebSocket client settings
#[derive(Debug, Clone)]
pub struct WsConfig {
    /// common client configuration.
    pub client_config: ClientConfig,
    /// whether to enable WS.
    pub enabled: bool,
    /// Max notifications per subscription.
    pub max_notifs_per_subscription: usize,
    /// Max number of redirections.
    pub max_redirections: usize,
}

#[cfg(test)]
mod check_mtls_requires_tls_tests {
    use super::check_mtls_requires_tls;

    #[test]
    fn plaintext_is_accepted() {
        assert!(check_mtls_requires_tls(false, false).is_ok());
    }

    #[test]
    fn tls_without_mtls_is_accepted() {
        assert!(check_mtls_requires_tls(true, false).is_ok());
    }

    #[test]
    fn mtls_on_top_of_tls_is_accepted() {
        assert!(check_mtls_requires_tls(true, true).is_ok());
    }

    #[test]
    fn mtls_without_tls_is_rejected() {
        let err = check_mtls_requires_tls(false, true).unwrap_err();
        assert!(err.contains("`enable_mtls` requires `enable_tls`"));
    }
}
