// Copyright (c) 2023 MASSA LABS <info@massa.net>

use massa_time::MassaTime;
use std::path::PathBuf;

/// Client common settings.
/// the client common settings
#[derive(Debug, Clone)]
pub struct ClientConfig {
    /// maximum size in bytes of a request.
    pub max_request_body_size: u32,
    /// timeout of an request.
    pub request_timeout: MassaTime,
    /// maximum concurrent requests.
    pub max_concurrent_requests: usize,
    /// certificate_store, `Native` or `WebPki`
    ///
    /// Deprecated: this setting is currently ignored. The underlying `jsonrpsee` client no
    /// longer exposes a trust-store selection, and TLS is instead enabled by using an
    /// `https`/`wss` url, validated against the platform trust store. It is kept to avoid
    /// breaking existing configuration files.
    pub certificate_store: String,
    /// JSON-RPC request object id data type, `Number` or `String`
    pub id_kind: String,
    /// max length for logging for requests and responses. Logs bigger than this limit will be truncated.
    pub max_log_length: u32,
    /// custom headers to pass with every request.
    pub headers: Vec<(String, String)>,
}

/// Http client settings.
/// the Http client settings
#[derive(Debug, Clone)]
pub struct HttpConfig {
    /// common client configuration.
    pub client_config: ClientConfig,
    /// whether to enable HTTP.
    pub enabled: bool,
}

/// gRPC client TLS settings.
/// the gRPC client TLS settings
#[derive(Debug, Clone)]
pub struct GrpcTlsConfig {
    /// name under which the server certificate is verified, also used for SNI.
    /// TLS verification is name-based while the client dials an IP, so this must match
    /// one of the subject alternative names of the server certificate. The self-signed
    /// certificates generated by the node always include "localhost".
    pub server_name: String,
    /// path to the certificate authority root used to verify the server certificate.
    pub certificate_authority_root_path: PathBuf,
    /// path to the client certificate, only for mTLS (must be set together with
    /// `client_private_key_path`).
    pub client_certificate_path: Option<PathBuf>,
    /// path to the client private key, only for mTLS (must be set together with
    /// `client_certificate_path`).
    pub client_private_key_path: Option<PathBuf>,
}

/// WebSocket client settings.
/// the WebSocket client settings
#[derive(Debug, Clone)]
pub struct WsConfig {
    /// common client configuration.
    pub client_config: ClientConfig,
    /// whether to enable WS.
    pub enabled: bool,
    /// Max notifications per subscription.
    pub max_notifs_per_subscription: usize,
    /// Max number of redirections.
    pub max_redirections: usize,
}
