(function() {var implementors = {};
implementors["consensus"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"consensus/error/enum.InternalError.html\" title=\"enum consensus::error::InternalError\">InternalError</a>","synthetic":false,"types":["consensus::error::InternalError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"consensus/error/enum.ConsensusError.html\" title=\"enum consensus::error::ConsensusError\">ConsensusError</a>","synthetic":false,"types":["consensus::error::ConsensusError"]}];
implementors["crypto"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"crypto/enum.CryptoError.html\" title=\"enum crypto::CryptoError\">CryptoError</a>","synthetic":false,"types":["crypto::error::CryptoError"]}];
implementors["models"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"models/error/enum.ModelsError.html\" title=\"enum models::error::ModelsError\">ModelsError</a>","synthetic":false,"types":["models::error::ModelsError"]}];
implementors["network"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"network/enum.NetworkError.html\" title=\"enum network::NetworkError\">NetworkError</a>","synthetic":false,"types":["network::error::NetworkError"]}];
implementors["pool"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"pool/enum.PoolError.html\" title=\"enum pool::PoolError\">PoolError</a>","synthetic":false,"types":["pool::error::PoolError"]}];
implementors["protocol_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"protocol_exports/enum.ProtocolError.html\" title=\"enum protocol_exports::ProtocolError\">ProtocolError</a>","synthetic":false,"types":["protocol_exports::error::ProtocolError"]}];
implementors["time"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"time/enum.TimeError.html\" title=\"enum time::TimeError\">TimeError</a>","synthetic":false,"types":["time::error::TimeError"]}];
implementors["wallet"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wallet/enum.WalletError.html\" title=\"enum wallet::WalletError\">WalletError</a>","synthetic":false,"types":["wallet::error::WalletError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()