(function() {var implementors = {};
implementors["massa_consensus_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus_exports/error/enum.InternalError.html\" title=\"enum massa_consensus_exports::error::InternalError\">InternalError</a>","synthetic":false,"types":["massa_consensus_exports::error::InternalError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus_exports/error/enum.ConsensusError.html\" title=\"enum massa_consensus_exports::error::ConsensusError\">ConsensusError</a>","synthetic":false,"types":["massa_consensus_exports::error::ConsensusError"]}];
implementors["massa_execution_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_execution_exports/enum.ExecutionError.html\" title=\"enum massa_execution_exports::ExecutionError\">ExecutionError</a>","synthetic":false,"types":["massa_execution_exports::error::ExecutionError"]}];
implementors["massa_final_state"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_final_state/enum.FinalStateError.html\" title=\"enum massa_final_state::FinalStateError\">FinalStateError</a>","synthetic":false,"types":["massa_final_state::error::FinalStateError"]}];
implementors["massa_graph"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_graph/error/enum.GraphError.html\" title=\"enum massa_graph::error::GraphError\">GraphError</a>","synthetic":false,"types":["massa_graph::error::GraphError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_graph/error/enum.InternalError.html\" title=\"enum massa_graph::error::InternalError\">InternalError</a>","synthetic":false,"types":["massa_graph::error::InternalError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_graph/error/enum.LedgerError.html\" title=\"enum massa_graph::error::LedgerError\">LedgerError</a>","synthetic":false,"types":["massa_graph::error::LedgerError"]}];
implementors["massa_hash"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_hash/enum.MassaHashError.html\" title=\"enum massa_hash::MassaHashError\">MassaHashError</a>","synthetic":false,"types":["massa_hash::error::MassaHashError"]}];
implementors["massa_ledger"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_ledger/enum.LedgerError.html\" title=\"enum massa_ledger::LedgerError\">LedgerError</a>","synthetic":false,"types":["massa_ledger::error::LedgerError"]}];
implementors["massa_models"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_models/error/enum.ModelsError.html\" title=\"enum massa_models::error::ModelsError\">ModelsError</a>","synthetic":false,"types":["massa_models::error::ModelsError"]}];
implementors["massa_network_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_network_exports/enum.NetworkError.html\" title=\"enum massa_network_exports::NetworkError\">NetworkError</a>","synthetic":false,"types":["massa_network_exports::error::NetworkError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_network_exports/enum.NetworkConnectionErrorType.html\" title=\"enum massa_network_exports::NetworkConnectionErrorType\">NetworkConnectionErrorType</a>","synthetic":false,"types":["massa_network_exports::error::NetworkConnectionErrorType"]}];
implementors["massa_pool"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_pool/enum.PoolError.html\" title=\"enum massa_pool::PoolError\">PoolError</a>","synthetic":false,"types":["massa_pool::error::PoolError"]}];
implementors["massa_proof_of_stake_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_proof_of_stake_exports/error/enum.ProofOfStakeError.html\" title=\"enum massa_proof_of_stake_exports::error::ProofOfStakeError\">ProofOfStakeError</a>","synthetic":false,"types":["massa_proof_of_stake_exports::error::ProofOfStakeError"]}];
implementors["massa_protocol_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_protocol_exports/enum.ProtocolError.html\" title=\"enum massa_protocol_exports::ProtocolError\">ProtocolError</a>","synthetic":false,"types":["massa_protocol_exports::error::ProtocolError"]}];
implementors["massa_time"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_time/enum.TimeError.html\" title=\"enum massa_time::TimeError\">TimeError</a>","synthetic":false,"types":["massa_time::error::TimeError"]}];
implementors["massa_wallet"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_wallet/enum.WalletError.html\" title=\"enum massa_wallet::WalletError\">WalletError</a>","synthetic":false,"types":["massa_wallet::error::WalletError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()