(function() {var implementors = {};
implementors["massa_consensus"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus/error/enum.InternalError.html\" title=\"enum massa_consensus::error::InternalError\">InternalError</a>","synthetic":false,"types":["massa_consensus::error::InternalError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus/error/enum.ConsensusError.html\" title=\"enum massa_consensus::error::ConsensusError\">ConsensusError</a>","synthetic":false,"types":["massa_consensus::error::ConsensusError"]}];
implementors["massa_hash"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_hash/enum.MassaHashError.html\" title=\"enum massa_hash::MassaHashError\">MassaHashError</a>","synthetic":false,"types":["massa_hash::error::MassaHashError"]}];
implementors["massa_models"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_models/error/enum.ModelsError.html\" title=\"enum massa_models::error::ModelsError\">ModelsError</a>","synthetic":false,"types":["massa_models::error::ModelsError"]}];
implementors["massa_network"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_network/enum.NetworkError.html\" title=\"enum massa_network::NetworkError\">NetworkError</a>","synthetic":false,"types":["massa_network::error::NetworkError"]}];
implementors["massa_pool"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_pool/enum.PoolError.html\" title=\"enum massa_pool::PoolError\">PoolError</a>","synthetic":false,"types":["massa_pool::error::PoolError"]}];
implementors["massa_protocol_exports"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_protocol_exports/enum.ProtocolError.html\" title=\"enum massa_protocol_exports::ProtocolError\">ProtocolError</a>","synthetic":false,"types":["massa_protocol_exports::error::ProtocolError"]}];
implementors["massa_time"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_time/enum.TimeError.html\" title=\"enum massa_time::TimeError\">TimeError</a>","synthetic":false,"types":["massa_time::error::TimeError"]}];
implementors["massa_wallet"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_wallet/enum.WalletError.html\" title=\"enum massa_wallet::WalletError\">WalletError</a>","synthetic":false,"types":["massa_wallet::error::WalletError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()