name: Sign Multiple Universal macOS Binaries
description: Sign multiple macOS binaries
author: MassaLabs

inputs:
  paths:
    description: Paths to binaries or app bundles to sign (space-separated)
    required: true
  certificate-p12-base64:
    description: Base64 certificate
    required: true
  certificate-password:
    description: Certificate password
    required: true
  signing-identity:
    description: Signing identity
    required: true
  entitlements:
    description: Path to entitlements file (optional)
    required: false

runs:
  using: "composite"
  steps:

    - name: Import Apple signing certificate
      uses: Apple-Actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ inputs.certificate-p12-base64 }}
        p12-password: ${{ inputs.certificate-password }}

    - name: Sign binaries and app bundles
      run: |
        echo "🔐 Starting signing process..."

        for path in ${{ inputs.paths }}; do
          echo "📝 Signing: $path"

          ENTITLEMENTS_ARG=""
          if [[ -n "${{ inputs.entitlements }}" ]]; then
            echo "📄 Using entitlements file: ${{ inputs.entitlements }}"
            if [[ ! -f "${{ inputs.entitlements }}" ]]; then
              echo "❌ Error: Entitlements file '${{ inputs.entitlements }}' does not exist"
            exit 1
            fi
            ENTITLEMENTS_ARG="--entitlements ${{ inputs.entitlements }}"
          fi

          codesign --force --options runtime --timestamp $ENTITLEMENTS_ARG\
            --sign "${{ inputs.signing-identity }}" "$path"

          echo "🔍 Verifying signature for: $path"
          codesign --verify --deep --strict --verbose=2 "$path"
        done
      shell: bash
