[package]
name = "massa_serialization"
version.workspace = true
authors = ["Massa Labs <info@massa.net>"]
edition.workspace = true

[features]

[dependencies]
displaydoc = {workspace = true}
thiserror = {workspace = true}
nom = {workspace = true}
unsigned-varint = {workspace = true, "features" = ["nom"]}
num = {workspace = true}

[dev-dependencies]
paste = {workspace = true}
