= FAQ
:toc:

== General questions

=== What are the hardware requirements?
The philosophy of Massa is to be as decentralized as possible. To fulfill this goal, we aim to have low hardware requirements so that many people can run nodes.
Right now 4 cores and 8 GB of RAM should be enough to run a node. As the number of transactions increase it might not be sufficient anymore. Ultimately, our plan is that the mainnet fits on a desktop computer with 8 cores, 16 GB RAM and 1TB disk.

=== Can it run on a VPS?

You can use a VPS to run a node. Pros of VPS is that they have a high availability and are easy to configure. Cons are that nodes running on a VPS can lead to centralization if a lot of nodes running on the same provider (e.g. AWS).

=== How to run a node in background?
You can run the following command in the terminal:
----
nohup cargo run --release &
----
the output will go to the `nohup.out` file. You will be able to close the terminal safely then.
To kill the app you'll have to use `pkill -f massa-node`.
You can also use link:https://help.ubuntu.com/community/Screen[screen] or link:http://manpages.ubuntu.com/manpages/cosmic/man1/tmux.1.html[tmux] for example.

=== Will Massa support smart contracts?
We will try to support both the EVM for retro compatibility, and a specific WASM engine that fully leverages the Massa protocol, allows developing in many usual languages, and introduces several innovations (e.g. autonomous contracts).

We are currently finishing the specification of the smart contract engine. The development of a preliminary version of the  engine will start after the first release of the testnet.

We are planning to use a WASM interpreter and there will be some exciting features, such as self-wakeup, a bit like what is introduced here: https://arxiv.org/pdf/2102.10784.pdf

=== What ports does the MASSA use?

By default Massa use the port 33033 (TCP/UDP).

=== How to restart the Node?

* Ubuntu :  ctrl + c for killing the process and `RUST_BACKTRACE=full cargo run --release |& tee logs.txt`
* Windows :  ctrl + c for killing the process and `cargo run --release`
* Mac Os :  ctrl + c for killing the process and `RUST_BACKTRACE=full cargo run --release > logs.txt 2>&1`

== Balance and wallet

=== How to migrate from one server to another without loosing staked amount and tokens?

You need to backup the file wallet.dat and migrate it in the massa-client folder on your new server. If you have bought rolls, you also need to register the key used to buy roll to start staking (see link:docs/staking.adoc[Staking]).

=== Why is a balance in the client and in the explorer different?

It may mean that you node is desynchronized. Try to restart your node (don't forget to save your wallet file !).

=== Does the command `cargo run -- --wallet wallet.dat` override my existing wallet?

No, it loads the wallet if it exists, otherwise it creates it.

=== Where is the wallet.dat located?

In the massa-client directory.

== Rolls and staking

=== I have bought rolls but the command `next_draws` doesn't show anything.
Our Proof-of-Stake implementation is made of cycles. Each cycle last for 10 periods, which correspond to 320 blocks, or 160 seconds. The `next_draws` command in the client outputs the next block creation opportunity for the provided address. Currently, if the address is not selected for a block creation in this cycle the command does not output anything. Try again in a few minutes and this time you might be selected for block creation in the current cycle!
In a future version of the API we will provide clearer messages to make it clear that everything is working as intended.

=== Do I need to register the keys after subsequent purchases of ROLLs, or do they get stacked automatically?

For now they don't stack automatically. In the future we will add a feature allowing autocompounding. 
That being said, some people appear to have done that very early in the project. Feel free to ask on the link:https://discord.com/invite/TnsJQzXkRN[Discord] server :).

=== Why command "next_draws" shows me an empty line?

If you want to see the next block that you will create the command is next_draws <your_address>

=== I can buy, send, sell ROLLs and MAS without fee. When should I increase fee >0?

For the moment, there are only a few transactions at the same time and so most created blocks are empty. This means that your operation will be added to a block even if the fee is zero.
We will communicate if you need to increase the fee.

=== I am staking ROLLs but my wallet info doesn't change. When i get my first staking rewards?

You need to wait that your rolls becomes active (around 8 minutes →  3 cycles of 10 periods (one period is 32 blocks = 16 sec)

== Testnet and rewards

=== I want to stake more! Can i abuse the faucet bot to get more coins?

You can claim testnet token every 24h, this tokens are worthless, you won't have advantage on the others by doing that.

=== Will the amount of staked Rolls affect Testnet rewards?

We are still figuring out the right way to reward participation in the testnet. However, the general idea will be to reward the stability of the node rather than the amount stake. Trying to buy more rolls for example by gaming the faucet is thus useless.
We will communicate information later on how we will rank the node stability.

== Common issues

=== Ping too high issue

=== Why command "wallet_info" response me back: "No balance info available. Is your node running?"

It means that there are no scheduled slots in current cycle.

=== "Server error response status: 500 Internal Server Error - error selecting draw : ReceiveChannelError("Could not retrieve selection draws: Proof of stake cycle unavailable trying to get PoS draw rolls/seed for cycle 4893 thread 0 which is unavailable")"





