# Staking

In Massa, the minimal number of coins to be able to stake is 500 MAS (which is called one "roll").
The total initial supply is 500m MAS, so in theory, there could be 1 million people staking.

Addresses are randomly selected to stake (create blocks) in all threads, based on the number of rolls they possess.
The list of stakers and their rolls can be seen link:https://test.massa.net/#staking[there].

Rolls can be bought with Massa coins or sold to get the coins back.
If you already have more than 500 coins, you can continue this tutorial, otherwise you can ask coins from us in the link:https://discord.com/invite/TnsJQzXkRN[Discord] testnet channel.

## Buying rolls


Get the address that has coins in your wallet:
----
wallet_info
----

Buy rolls with it: put your address 
----
buy_rolls <address>  <roll count> <fee>
----

It should take less than one minute for your roll to become final, check with:
----
wallet_info
----

## Telling your node to start staking with your rolls

Get the private key that has rolls in your wallet:
----
wallet_info
----

Register your private key so that your node start to stake with it:
----
register_staking_keys <your_private_key>
----


Now you should wait some time so that your rolls become active: about 3 cycles of 10 periods (one period is 32 blocks - 16 sec), so about 8 minutes.

You can check if your rolls are active with the same command:
----
wallet_info
----
