(function() {var implementors = {
"massa_api_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_api_exports/error/enum.ApiError.html\" title=\"enum massa_api_exports::error::ApiError\">ApiError</a>"]],
"massa_cipher":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_cipher/enum.CipherError.html\" title=\"enum massa_cipher::CipherError\">CipherError</a>"]],
"massa_consensus_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus_exports/error/enum.LedgerError.html\" title=\"enum massa_consensus_exports::error::LedgerError\">LedgerError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus_exports/error/enum.InternalError.html\" title=\"enum massa_consensus_exports::error::InternalError\">InternalError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_consensus_exports/error/enum.ConsensusError.html\" title=\"enum massa_consensus_exports::error::ConsensusError\">ConsensusError</a>"]],
"massa_execution_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_execution_exports/enum.ExecutionError.html\" title=\"enum massa_execution_exports::ExecutionError\">ExecutionError</a>"]],
"massa_factory_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_factory_exports/enum.FactoryError.html\" title=\"enum massa_factory_exports::FactoryError\">FactoryError</a>"]],
"massa_final_state":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_final_state/enum.FinalStateError.html\" title=\"enum massa_final_state::FinalStateError\">FinalStateError</a>"]],
"massa_hash":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_hash/enum.MassaHashError.html\" title=\"enum massa_hash::MassaHashError\">MassaHashError</a>"]],
"massa_ledger_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_ledger_exports/enum.LedgerError.html\" title=\"enum massa_ledger_exports::LedgerError\">LedgerError</a>"]],
"massa_models":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_models/error/enum.ModelsError.html\" title=\"enum massa_models::error::ModelsError\">ModelsError</a>"]],
"massa_network_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_network_exports/enum.NetworkError.html\" title=\"enum massa_network_exports::NetworkError\">NetworkError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_network_exports/enum.NetworkConnectionErrorType.html\" title=\"enum massa_network_exports::NetworkConnectionErrorType\">NetworkConnectionErrorType</a>"]],
"massa_pos_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_pos_exports/enum.PosError.html\" title=\"enum massa_pos_exports::PosError\">PosError</a>"]],
"massa_protocol_exports":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_protocol_exports/enum.ProtocolError.html\" title=\"enum massa_protocol_exports::ProtocolError\">ProtocolError</a>"]],
"massa_serialization":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"struct\" href=\"massa_serialization/struct.DeserializeError.html\" title=\"struct massa_serialization::DeserializeError\">DeserializeError</a>&lt;'a&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_serialization/enum.SerializeError.html\" title=\"enum massa_serialization::SerializeError\">SerializeError</a>"]],
"massa_signature":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_signature/enum.MassaSignatureError.html\" title=\"enum massa_signature::MassaSignatureError\">MassaSignatureError</a>"]],
"massa_time":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_time/enum.TimeError.html\" title=\"enum massa_time::TimeError\">TimeError</a>"]],
"massa_versioning_worker":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_versioning_worker/versioning_factory/enum.FactoryError.html\" title=\"enum massa_versioning_worker::versioning_factory::FactoryError\">FactoryError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_versioning_worker/versioning/enum.StateAtError.html\" title=\"enum massa_versioning_worker::versioning::StateAtError\">StateAtError</a>"]],
"massa_wallet":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"massa_wallet/enum.WalletError.html\" title=\"enum massa_wallet::WalletError\">WalletError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()