[package]
name = "massa_test_framework"
version = "28.5.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models"}
massa_signature = { path = "../massa-signature" }
tracing-subscriber = { workspace = true, features = ["env-filter"]}

[features]
test-exports = ["massa_models/test-exports"]
